name: Firebase Deploy
on:
  push:
    branches:
      - main

jobs:
  install:
    name: Git Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Install Dependencies
        run: npm install
  build:
    name: Git Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: npm run build
  archive-upload:
    name: Git Archive Upload
    runs-on: ubuntu-latest
    steps:
      - name: Archive dist
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
    
  archive-download:
    name: Git Archive Download 
    needs: archive-upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      - name: Download dist
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
  deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
